/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.Vector;

public class MiLista implements MiniList {

    private Container obj = null;
	@Override
	public boolean add(Object elemento) throws NullPointerException {
		
//		if(elemento == null)
//			throw new NullPointerException("no se pueden nulos.");
//		
//		obj = elemento;
//		
		

		return true;
	}

	
	
	@Override
	public boolean contains(Object elemento) {
		
		boolean retorno = false;
		
		if(elemento !=null){
		
			retorno = true;
			
		}
		return retorno;
	}

	@Override
	public boolean delete(Object elemento) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean delete(int elemento) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean set(Object elemento, int posicion) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public Object get(int posicion) {
		
		return null;
	}

	@Override
	public int size() {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void clear() {
		// TODO Auto-generated method stub
		
	}
	private class Container {
		Object obj = null;
		Container next = null;
		
	}

}

